spring:
  application:
    name: schoolwall
  datasource:
    url: jdbc:mysql://localhost:3306/schoolwall?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true # 确保数据库名为 schoolwall
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: "{noop}admin"

  flyway: # Flyway 配置
    enabled: true
    locations: classpath:db/migration # 指定SQL脚本的位置，与文件路径一致
    baseline-on-migrate: true # 第一次运行时，如果数据库非空，则创建baseline版本
    repair-on-migrate: true # 修复数据库状态，确保迁移脚本可以正确执行

mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  charset:
    console: UTF-8&useUnicode
    file: UTF-8&useUnicode
  level:
    com.fy.schoolwall: DEBUG
    org.springframework: INFO
    # org.hibernate: INFO # 如果不使用JPA，可以移除或注释
    org.apache.ibatis: DEBUG
    org.flywaydb: DEBUG # 开启Flyway的日志，便于查看迁移过程
    org.springframework.security: DEBUG # 开启Spring Security的日志，便于调试
